# Add f.e. 'Extension:B2B-Suite' label if issue contains the word / regex 'Extension:B2B-Suite'
version: 1
appendOnly: true #only add labels never remove them automatically
labels:
  - label: "Platform(Default)"
    body: 'Platform\(Default\)'
  - label: "Extension:Commercial"
    body: "Extension:Commercial"
  - label: "Extension:B2B-Suite"
    body: "Extension:B2B-Suite"
  - label: "Extension:CMS-Extensions"
    body: "Extension:CMS-Extensions"
  - label: "Extension:Custom-Products"
    body: "Extension:Custom-Products"
  - label: "Extension:Dynamic-Access"
    body: "Extension:Dynamic-Access"
  - label: "Extension:Language-Pack"
    body: "Extension:Language-Pack"
  - label: "Extension:Migration-Tool"
    body: "Extension:Migration-Tool"
  - label: "Extension:PayPal-Integration"
    body: "Extension:PayPal-Integration"
  - label: "Extension:Publisher"
    body: "Extension:Publisher"
  - label: "Extension:Social-Shopping"
    body: "Extension:Social-Shopping"
