title: "Proposals"
body:
  - type: textarea
    id: content
    attributes:
      label: Change description
      description: |
        Please describe your proposed change in detail.
      value: |
        # Benefit <!-- What is the benefit of the change? -->
        
        # Description  <!-- Please describe your proposed change in detail. -->
        
        # Effort <!-- How much effort do you expect is required to make the change? -->

        # Break strategy <!-- Can this change lead to any breaks? If so, how should they be handled -->
    validations:
      required: true
