name: Downstream

on:
  pull_request:
  merge_group:
  workflow_dispatch:
    inputs:
      nightly:
        default: ""
  workflow_call:
    inputs:
      nightly:
        type: string
        default: ""

permissions:
  contents: read
  id-token: write

jobs:
  rufus:
    name: Rufus
    runs-on: ubuntu-24.04
    if: ${{ startsWith(github.repository, 'shopware/') && !github.event.pull_request && github.event_name != 'merge_group'}}
    steps:
      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Rufus
        uses: shopware/github-actions/downstream@main
        if: steps.check.outputs.has-permission
        with:
          repo: shopware/rufus
          workflow: Downstream
          ref: .auto
          timeout: 30m
          token-scope: shopware
          identity: ShopwareDownstream
          env:
            NIGHTLY=${{ inputs.nightly }}
  
  commercial:
    name: Commercial
    runs-on: ubuntu-24.04
    if: startsWith(github.repository, 'shopware/')
    steps:
      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commercial
        uses: shopware/github-actions/downstream@main
        if: steps.check.outputs.has-permission
        with:
          repo: shopware/SwagCommercial
          workflow: Downstream
          ref: .auto
          timeout: 60m
          token-scope: shopware
          identity: ShopwareDownstream
          env:
            NIGHTLY=${{ inputs.nightly }}

  downstream-check:
    if: always()
    needs:
    # fix with shopware/shopware#6556
    # - rufus
    - commercial

    runs-on: Ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: rufus, commercial
        jobs: ${{ toJSON(needs) }}